apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlacards-deployment
  labels:
    app: parlacards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlacards
  template:
    metadata:
      labels:
        app: parlacards
    spec:
      containers:
        - name: parlacards
          image: parlacards
          ports:
            - containerPort: 3000
          env:
            - name: VITE_PARLASSETS_URL
              value: https://parlassets-ljubljana.lb.djnd.si/v1/parlassets
            - name: VITE_PARLADATA_URL
              value: https://parladata.lb.djnd.si/v3
            - name: VITE_PARLACARDS_URL
              value: https://parlacards.lb.djnd.si
            - name: VITE_PARLASITE_URL
              value: https://parlasite.lb.djnd.si
