apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlacards-ua
  labels:
    app: parlacards-ua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlacards-ua
  template:
    metadata:
      labels:
        app: parlacards-ua
    spec:
      containers:
        - name: parlacards-ua
          image: parlacards-ua
          ports:
            - containerPort: 3000
          env:
            - name: VITE_PARLASSETS_URL
              value: https://parlassets-ua.lb.djnd.si
            - name: VITE_PARLADATA_URL
              value: https://parladata-ua.lb.djnd.si/v3
            - name: VITE_PARLACARDS_URL
              value: https://parlacards-ua.lb.djnd.si
            - name: VITE_PARLASITE_URL
              value: https://parlameter.chesno.org
