apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlacards-ajdovscina-deployment
  labels:
    app: parlacards-ajdovscina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlacards-ajdovscina
  template:
    metadata:
      labels:
        app: parlacards-ajdovscina
    spec:
      containers:
        - name: parlacards-ajdovscina
          image: parlacards-ajdovscina
          ports:
            - containerPort: 3000
          env:
            - name: VITE_PARLASSETS_URL
              value: https://parlassets-ajdovscina.lb.djnd.si
            - name: VITE_PARLADATA_URL
              value: https://parladata-ajdovscina.lb.djnd.si/v3
            - name: VITE_PARLACARDS_URL
              value: https://parlacards-ajdovscina.lb.djnd.si
            - name: VITE_PARLASITE_URL
              value: https://parlasite-ajdovscina.lb.djnd.si
