apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlacards-hrastnik-deployment
  labels:
    app: parlacards-hrastnik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlacards-hrastnik
  template:
    metadata:
      labels:
        app: parlacards-hrastnik
    spec:
      containers:
        - name: parlacards-hrastnik
          image: parlacards-hrastnik
          ports:
            - containerPort: 3000
          env:
            - name: VITE_PARLASSETS_URL
              value: https://parlassets-hrastnik.lb.djnd.si
            - name: VITE_PARLADATA_URL
              value: https://parladata-hrastnik.lb.djnd.si/v3
            - name: VITE_PARLACARDS_URL
              value: https://parlacards-hrastnik.lb.djnd.si
            - name: VITE_PARLASITE_URL
              value: https://parlasite-hrastnik.lb.djnd.si
