apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlacards-ajdovscina
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - parlacards-ajdovscina.lb.djnd.si
      secretName: parlacards-ajdovscina-tls
  rules:
    - host: parlacards-ajdovscina.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlacards-ajdovscina
                port:
                  number: 3000
