apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite-vii
  labels:
    app: parlasite-vii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite-vii
  template:
    metadata:
      labels:
        app: parlasite-vii
    spec:
      containers:
        - name: parlasite-vii
          image: parlasite-slovenija
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
          env:
            - name: PARLASITE_LEADER_ID
              value: "261"
            - name: PARLASITE_ROOT_ORG_ID
              value: "293"
            - name: PARLASITE_MANDATE_ID
              value: "3"
            - name: PARLASITE_DEFAULT_CARD_DATE
              value: "2018-06-20"
