apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlasite-vii
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-sandbox"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vii.parlameter.si
      secretName: parlasite-vii-tls
  rules:
    - host: vii.parlameter.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlasite-vii
                port:
                  number: 3066
