apiVersion: apps/v1
kind: Deployment
metadata:
  name: parlasite-ajdovscina-deployment
  labels:
    app: parlasite-ajdovscina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parlasite-ajdovscina
  template:
    metadata:
      labels:
        app: parlasite-ajdovscina
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: parlasite-ajdovscina
          image: parlasite-ajdovscina
          ports:
            - containerPort: 3066
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m
