apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlasite-ajdovscina
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - parlasite-ajdovscina.lb.djnd.si
      secretName: parlasite-ajdovscina-tls
  rules:
    - host: parlasite-ajdovscina.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlasite-ajdovscina
                port:
                  number: 3066
