apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parlasite-bosna
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - parlasite-bosna.lb.djnd.si
      secretName: parlasite-bosna-tls
  rules:
    - host: parlasite-bosna.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parlasite-bosna
                port:
                  number: 3066
